### ISSUE TITLE
Support for flutter web

### ISSUE THREAD

**Issue by ndungudedan** [keronei/mpesa_flutter_plugin#5]
I tried to integrate your plugin to a flutter web project but it does not work.. In android it works well with the same code base

**Comment by Mozoku** [comment]
i'm guessing no action on this? or did you find a work around?

**Comment by ndungudedan** [comment]
Error message:"Unsupported operation: Platform._version" .According to flutter The top-level http methods use a dart:io-based client that doesn't work on the browser..
[issue track](https://github.com/flutter/flutter/issues/64539).
For the moment no action on this

**Comment by talhasaleem81** [comment]
Hey! i tried your plugin but the popup for the M-Pesa pin doesn't came up for me, but i got the successful response from it:


"I/flutter (20468): TRANSACTION RESULT: {MerchantRequestID: 17415-1095797-1, CheckoutRequestID: ws_CO_260520211337404519, ResponseCode: 0, ResponseDescription: Success. Request accepted for processing, CustomerMessage: Success. Request accepted for processing}"

Also i'm trying it from Asia and if i gave my number then it says:

"error: +9233xxxxxxxx need be in international format"

otherwise if i use another kenyan number (254729050401) then it works fine.
Thanks in advance

**Comment by ndungudedan** [comment]
Hey talhasaleem81.
I dont think its possible to use mpesa services in asia..Its only available to east africa.
The mpesa pin pop up may delay occassionally.
